fixed compiler and include locations
logrhythm/CodeCoverage pull request #10
Opened 2018-06-11 22:48 UTC by DylanSchneider

Story: https://jira.logrhythm.com/browse/NM-1104

2018-06-11 23:13 UTC, alexweltman requested changes
wow Dylan, I expected better out of AEPi

2018-06-12 19:09 UTC, KjellKod commented on scripts/CodeCoverage.py
> +        return '-DCMAKE_CXX_COMPILER=/usr/local/gcc/bin/g++'
I don't think this is correct.  Shouldn't it be `/usr/bin/g++`?

2018-06-12 19:11 UTC, KjellKod commented on scripts/CodeCoverage.py
> +        return '-DCMAKE_CXX_COMPILER=/usr/local/gcc/bin/g++'
I stand corrected!  from the package files I see that it is `/usr/local/gcc/bin`

2018-06-12 19:13 UTC, KjellKod commented on scripts/CodeCoverage.py
> +        return '--gcov-executable /usr/bin/gcov'
This would point to gcov for version `4.8.5` while the compiler in `/usr/local/gcc/bin` points to a newer version of gcc

2018-06-12 19:14 UTC, KjellKod commented on scripts/CodeCoverage.py
> +        return '--gcov-executable /usr/bin/gcov'
I.e. shouldn it stay `/usr/local/gcc/bin/gcov`?

2018-06-12 19:39 UTC, KjellKod commented
👍

2018-06-12 19:39 UTC, KjellKod approved these changes
nice change

2018-06-12 19:39 UTC, merged