Fix cov script
logrhythm/CodeCoverage pull request #12
Opened 2018-06-27 06:41 UTC by DylanSchneider

Story: https://jira.logrhythm.com/browse/NM-1104

2018-06-28 22:24 UTC, josh-cogdill requested changes

2018-06-28 22:24 UTC, josh-cogdill commented on scripts/CodeCoverage.py
> +        for f in files:
I would name the loop variable something more descriptive other than `f`. Maybe `file`

2018-06-28 22:24 UTC, josh-cogdill commented on scripts/CodeCoverage.py
> +    # ProbeTransmogrifier builds both Probe_Transmogrifier and ProbeTransmogrifier. ProbeTransmogrifier has the code we want to cover, not Probe_Transmnogrifier
typo at the end of this comment `Probe_TransmNogrifier`

2018-07-02 17:22 UTC, DylanSchneider commented on scripts/CodeCoverage.py
> +        for f in files:
just don't want to name it `file` because then it'll overwrite that keyword. will use `filename`.

2018-07-24 21:39 UTC, josh-cogdill approved these changes

2018-07-25 16:52 UTC, merged